name: CI
run-name: >
  CI - ${{ github.event_name == 'workflow_dispatch' && (inputs.deploy-to-dev && 'with Deployment to Dev' || 'without Deployment') || 'with Deployment to Dev' }} - 
  ${{ github.event_name == 'workflow_dispatch' && inputs.target-infra || 'abc' }}

on:
  workflow_dispatch:
    inputs:
      deploy-to-dev:
        description: 'Deploy to Dev'
        default: true
        type: boolean
      target-infra:
        description: 'Target infra'
        required: true
        default: 'abc'
        type: choice
        options:
          - abc
          - def
  push:
    branches:
      - main

jobs:
  setup-env-var:
    runs-on: ubuntu-latest
    outputs:
      deploy-to-dev: ${{ steps.set-vars.outputs.deploy_to_dev }}
      target-infra: ${{ steps.set-vars.outputs.target_infra }}
    steps:
      - name: Set deploy and target vars
        id: set-vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "deploy_to_dev=${{ inputs.deploy-to-dev }}" >> $GITHUB_OUTPUT
            echo "target_infra=${{ inputs.target-infra }}" >> $GITHUB_OUTPUT
          else
            echo "deploy_to_dev=true" >> $GITHUB_OUTPUT
            echo "target_infra=abc" >> $GITHUB_OUTPUT
          fi

  build-workflow:
    needs: setup-env-var
    runs-on: ubuntu-latest
    steps:
      - name: Print resolution
        env:
          deploy_to_dev: ${{ needs.setup-env-var.outputs.deploy-to-dev }}
          target_infra: ${{ needs.setup-env-var.outputs.target-infra }}
        run: |
          echo "deploy-to-dev = ${deploy_to_dev}"
          echo "target-infra = ${target_infra}"