name: CI
run-name: ${{github.event_name == 'push' && 'CI with Deployment to Dev || 
            (inputs.deploy-to-dev && 'CI with Deployment to Dev' || 'CI without Deployment') }} - ${{ inputs.target-infra }}
on:
  workflow_dispatch:
    inputs:
      deploy-to-dev:
        description: 'Deploy to Dev'
        default: true
        type: boolean
      target-infra:
        description: 'Target infra'
        required: true
        default: 'abc'
        type: choice
        options:
          - abc
          - def
  push:
    branches:
      - main

jobs:
  setup-env-var:
    runs-on: 
      ubuntu-latest
    name: Setup Env Var
    outputs:
      deploy-to-dev: ${{ steps.deploy-to-dev.outputs.deploy-to-dev }}
      target-infra: ${{ inputs.target-infra == '' && 'abc' || inputs.target-infra}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Deploy to DEV?
        id: deploy-to-dev
        env: 
          deploy_to_dev: ${{ inputs.deploy-to-dev }}
        run:
          echo "deploy-to-dev=${deploy-to-dev:-true}" >> $GITHUB_OUTPUT

  build-workflow:
    runs-on: 
      ubuntu-latest
    name: Interpret build
    needs: setup-env-var
    steps:
      - name: Print resolution
        env:
          deploy_to_dev: ${{ needs.setup-env-var.outputs.deploy-to-dev }}
          target_infra: ${{ needs.setup-env-var.outputs.target-infra }}
        run: |
          echo "deploy-to-dev = ${deploy_to_dev}"
          echo "target-infra = ${target_infra}"

